### ISSUE TITLE
Id equals to 0 when FetchAllExceptStrategy used

### ISSUE THREAD

**Issue by vshmulskyi-nmt** [ASbeletsky/Cqrs.Core#1]
All other properties populate as expected.
Replacing Entity<> to IIdentifieble<> didn't solve the problem

StackTrace:	
at CqrsEase.EntityFrameworkCore.IQueriableExtensions.<>c__3`1.<BuildSelector>b__3_1(PropertyInfo prop)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, IEnumerable`1 bindings)
   at CqrsEase.EntityFrameworkCore.IQueriableExtensions.BuildSelector[T](IEnumerable`1 paths)
   at CqrsEase.EntityFrameworkCore.IQueriableExtensions.SelectOnly[T](IQueryable`1 queryable, IEnumerable`1 paths)
   at CqrsEase.EntityFrameworkCore.QueryHandlers.GetManyQueryHandler`1.Request(GetManyQuery`1 query)
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.

**Comment by ASbeletsky** [comment]
fixed in 1.0.4-rc version. closed
